### ISSUE TITLE
Remove diacritics not working...

### ISSUE THREAD

**Issue by joaobsantos** [moroshko/autosuggest-highlight#10]
I cant get the the remove diacritics to work. If i have a nme like João, i want it to match when i type joao...

Example:
https://github.com/mui-org/material-ui/blob/v1-beta/docs/src/pages/demos/autocomplete/IntegrationAutosuggest.js

Thx in advance, good work.

**Comment by nikdo** [comment]
Not sure what was not working. It is working just fine and [there is a test](https://github.com/moroshko/autosuggest-highlight/blob/master/src/match.test.js#L25) proving me correct. :) I think it is safe to close this issue.
