### ISSUE TITLE
Is this project still being worked on?

### ISSUE THREAD

**Issue by Lagicrus** [moroshko/autosuggest-highlight#16]
It has been a few years since the last update & version, and when I checked it seems there are some vulnerabilities in the package itself.

**Comment by rek** [comment]
I don't mind maintaining this for a while if any of the original authors are around and interested in opening it up.

**Comment by tomj** [comment]
https://www.npmjs.com/package/highlight-words-core looks like it may be a promising alternative

**Comment by DanielGibbsNZ** [comment]
This package is now being used by Material UI's Autocomplete component (https://material-ui.com/components/autocomplete/#highlights) so hopefully it gets maintained!

**Comment by JekRock** [comment]
@DanielGibbsNZ the package is not used in the Material UI Autocomplete. They just used it in a few of the examples on the documentation page

**Comment by Lagicrus** [comment]
> @DanielGibbsNZ the package is not used in the Material UI Autocomplete. They just used it in a few of the examples on the documentation page

That may be the case, but as it is so visible it would be expected that a large amount of people use it for that purpose, such as myself

**Comment by ChrisWiles** [comment]
I would say it is not being worked on. Dead

**Comment by anubra266** [comment]
> I don't mind maintaining this for a while if any of the original authors are around and interested in opening it up.

@rek DO you still want to work on this?
