### ISSUE TITLE
Special chars have unexpected behavior

### ISSUE THREAD

**Issue by AliaumeL** [moroshko/autosuggest-highlight#18]
When using French words containing the letter `œ` highlighting is not working properly. 

## Minimal code to reproduce 

```javascript
const myText = "œuvre pompes test";

const mySearch = "pompes";

const m = match(myText, mySearch);
const p = parse(myText, m);
```

## How the code behaves

```javascript 
m = [[7,13]]
p = [{"text":"œuvre p","highlight":false},{"text":"ompes ","highlight":true},{"text":"test","highlight":false}]
```
## How the code is expected to behave 
 
```javascript 
m = [[6,12]]
p = [{"text":"œuvre ","highlight":false},{"text":"pompes","highlight":true},{"text":" test","highlight":false}]
```

## Hypothesis

The character `œ` is somehow considered as having size two in the code of `match` which is inconsistent with Javascript's behavior when slicing strings.

**Comment by i5ik** [comment]
To get actual length of a unicode string (symbol length, not <string>.length) do this: Array.from(str).length

This might help patch this issue eventually.
