### ISSUE TITLE
Highlighter not matching special character variations

### ISSUE THREAD

**Issue by Fetz** [moroshko/autosuggest-highlight#3]
`Card`  is not matching `Cárd` and other variations

<img width="240" alt="screen shot 2016-06-15 at 14 31 02" src="https://cloud.githubusercontent.com/assets/1071113/16081546/dac53906-3305-11e6-8665-e73ee906928d.png">

**Comment by sergiokopplin** [comment]
Same for me.

**Comment by Fetz** [comment]
For the matching the text will need some kinda of normalization to remove diacritics/accents characters for the matching

http://stackoverflow.com/questions/227950/programatic-accent-reduction-in-javascript-aka-text-normalization-or-unaccentin
http://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript/5912746

example in similar library:
https://github.com/JedWatson/react-select/blob/0381c75ed1c490218919a6e2d474d94c3410979e/src/utils/stripDiacritics.js

npm modules that could be used:
https://github.com/andrewrk/node-diacritics
https://www.npmjs.com/package/underscore.string

**Comment by moroshko** [comment]
@Fetz @sergiokopplin Sorry it took so long. This is fixed now in [v3.0.0](https://github.com/moroshko/autosuggest-highlight/releases/tag/v3.0.0).
